coverage:
  status:
    project:
      default:
        target: 70%

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
  individual_components:
    - component_id: module_exception
      name: exception
      paths:
        - "src/Exception/**"
      coverage:
        target: 80%
    - component_id: module_type
      name: type
      paths:
        - "src/Type/**"
      coverage:
        target: 80%