name: Code Coverage
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, zip, apcu
          tools: phpunit:12.x
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Install composer dependencies
        run: composer install  --no-interaction --no-progress --prefer-dist
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}